spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    mybatis:
      config-location : classpath:mybatis-config.xml